### ISSUE TITLE
plz fix captcha error

### ISSUE THREAD

**Issue by NamasteIndia** [techyhoney/TikTok_Scrapper#2]
`Traceback (most recent call last):
  File "C:\Users\troy\Desktop\TikTok_Scrapper-master\TikTok.py", line 30, in <module>
    trending = api.byUsername(username,results)
  File "C:\Users\troy\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 601, in by_username
    return self.userPosts(
  File "C:\Users\troy\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 564, in user_posts
    res = self.get_data(url=api_url, **kwargs)
  File "C:\Users\troy\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 276, in get_data
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters`

**Comment by andrearama** [comment]
If you do not have too much data to scrape, you can do it for free with services like [this](https://www.influencerhunters.com/docs.html) or [this](https://tikapi.io/documentation/#section/Errors)

**Comment by hacknapier** [comment]
TikTok Captcha Solving Service is available here with demo to Login successfully into your TikTok Account.
https://rapidapi.com/flyCaptcha/api/flycaptcha
